### ISSUE TITLE
Add support for `focus_on_load` parameter in blocks

### ISSUE THREAD

**Issue by CGA1123** [CGA1123/slack-ruby-block-kit#126]
November 2021 Slack [Changelog](https://api.slack.com/changelog#changelog_date_2021-11) includes an additional `focus_on_load` parameter.

We should add support to these blocks for this parameter:
- [ ] Checkbox groups 
- [ ] Date picker element 
- [ ] Multi-select menu element
  - Static
  - External
  - User list 
  - Conversations list 
  - Public channels list 
- [ ] Plain-text input element 
- [ ] Radio button group element 
- [ ] Select menu element
  - Static
  - External
  - User list 
  - Conversations list 
  - Public channels list 
- [ ] Time picker element

**Comment by aka-nez** [comment]
Hi! Is it actual? :)

**Comment by CGA1123** [comment]
@aka-nez sorry, what do you mean?

**Comment by aka-nez** [comment]
@CGA1123 I mean that I feel the energy to make this contribution. But I saw a few fresh commits from you, and this question was about your plans for this issue. Do you have any? If not, I'm going to do that.

PS: Sorry for the misunderstanding. I'm not a native English speaker  :)

**Comment by CGA1123** [comment]
@aka-nez oh I see! No I don't have any plans to take this issue on myself, fell free to!

Would be happy to have your contributions 😄

**Comment by aka-nez** [comment]
@CGA1123 Hi! Should I update the changelog too?
