### ISSUE TITLE
Rendering `.blockkit` with ActionView template handling

### ISSUE THREAD

**Issue by bmorton** [CGA1123/slack-ruby-block-kit#177]
Hey!  As I mentioned in #175, we're working on improving how we handle interactions with Slack within our monolithic codebase at FireHydrant.  One thing that has made this substantially easier to work with is separating out our code that generates views into Rails' ActionView layer.  This path doesn't seem well-documented or well-traveled, but using `jbuilder` as inspiration, I've got an implementation in our codebase that handles turning a `index.json.blockkit`-style template into BlockKit JSON.

Essentially, it lets you write a view that looks like this:

### `index.json.blockkit`
```ruby
metadata.type "modal"
metadata.title @title

blocks.section do |section|
  section.plain_text text: "Hello, World!"
end
```

### `ExampleController`
```ruby
class ExampleController < ApplicationController
  def index
    @title = "Hello Ruby"
    render :index, formats: [:json]
  end
end
```

There's not much code to implement this as it's mostly glue between Rails and this library (along with some extra metadata stuff that sits alongside `blocks` in the response payload).  The biggest maintenance cost with this would be keeping up with and testing against new Rails versions to ensure broad support there.

Would this be worth including in this library?  Would it be better to keep it separate and maybe throw a link to that library?

**Comment by CGA1123** [comment]
I love this idea as a means to ease the flow of building Slack apps on Rails.

I think having this shipped as it's own independent gem would be better, allowing it to concern itself with rails specifics over time and not requiring non Rails users to take on those transitive dependencies when requiring this gem.

Very happy to direct people to this new Gem via the README!

**Comment by CGA1123** [comment]
Nice! Excited to see what comes out of this piece of work.

If there are additional to the API exposed by this library that would help, please do let me know and we can figure out what can be done!
