### ISSUE TITLE
Some input types missing ability to add `description` to `Composition::Option`

### ISSUE THREAD

**Issue by gabichuelas** [CGA1123/slack-ruby-block-kit#181]
Looks like the library allows `Composition::Option` objects to be created with a `description` parameter ([ref](https://github.com/CGA1123/slack-ruby-block-kit/blob/master/lib/slack/block_kit/composition/option.rb#L14)), but several input types are missing the ability to do so:
- [`StaticSelect`](https://github.com/CGA1123/slack-ruby-block-kit/blob/master/lib/slack/block_kit/element/static_select.rb#L32)
- [`MultiStaticSelect`](https://github.com/CGA1123/slack-ruby-block-kit/blob/master/lib/slack/block_kit/element/multi_static_select.rb#L42)
- [`RadioButtons`](https://github.com/CGA1123/slack-ruby-block-kit/blob/master/lib/slack/block_kit/element/radio_buttons.rb#L25)

While some others include it:
- [`Checkboxes`](https://github.com/CGA1123/slack-ruby-block-kit/blob/master/lib/slack/block_kit/element/checkboxes.rb#L27)

Happy to take care of this just wanted to put an issue up in case there was more context.

**Comment by CGA1123** [comment]
Hey @gabichuelas -- I think this is just an oversight!

**Comment by CGA1123** [comment]
Closed via #195 -- Thanks @resputin 🚀

Shipped in v0.25.0
