### ISSUE TITLE
JSON attribute should be `initial_options` instead of `initial_option`

### ISSUE THREAD

**Issue by caalberts** [CGA1123/slack-ruby-block-kit#45]
@CGA1123  Either this is a bug or Slack actually allows singular version of the attribute.

- `MultiExternalSelect` https://github.com/CGA1123/slack-ruby-block-kit/blob/371f2f2698d07d2ba2f361ae6bfca0539cf48889/lib/slack/block_kit/element/multi_external_select.rb#L52-L52
  - https://api.slack.com/reference/block-kit/block-elements#external_multi_select__fields
- `MultiStaticSelect` https://github.com/CGA1123/slack-ruby-block-kit/blob/371f2f2698d07d2ba2f361ae6bfca0539cf48889/lib/slack/block_kit/element/multi_static_select.rb#L80-L80
  - https://api.slack.com/reference/block-kit/block-elements#static_multi_select__fields

**Comment by anvox** [comment]
I didn't test it properly. It should be `initial_options`, `initial_option` is for single choice. You could verify it [here](https://app.slack.com/block-kit-builder/T02AARX7T#%7B%22blocks%22:%5B%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Farmhouse%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22%7D,%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Kin%20Khao%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22%7D,%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Ler%20Ros%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22%7D%5D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Pick%20an%20item%20from%20the%20dropdown%20list%22%7D,%22accessory%22:%7B%22type%22:%22static_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20an%20item%22,%22emoji%22:true%7D,%22initial_option%22:%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-1%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-2%22%7D%5D%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Pick%20an%20item%20from%20the%20dropdown%20list%22%7D,%22accessory%22:%7B%22type%22:%22multi_static_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20an%20item%22,%22emoji%22:true%7D,%22initial_options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D%5D,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-1%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-2%22%7D%5D%7D%7D%5D%7D)

Could you help to open a PR to fix it? @caalberts 
if you're busy, I'll back to fix it tomorrow. Thanks :)

**Comment by CGA1123** [comment]
Hey @caalberts 

This is correct. `MultiConversationsSelect`, `MultiChannelsSelect`, and `MultiUsersSelect` are also affected by being singular rather than plural.
