### ISSUE TITLE
Implement Slack::BlockKit::Layout::Header

### ISSUE THREAD

**Issue by CGA1123** [CGA1123/slack-ruby-block-kit#56]
https://api.slack.com/reference/block-kit/blocks#header

Add a block object for this and an associated helper in `Slack::BlockKit::Block.header`

**Comment by rspeicher** [comment]
Should this have a corresponding shortcut method in https://github.com/CGA1123/slack-ruby-block-kit/blob/3a632f2e81129483fb6913fe1f00d370ecf9ddce/lib/slack/block_kit/blocks.rb?

E.g.,

```ruby
blocks = Slack::BlockKit.blocks do |b|
  b.header(text: ":rocket: Foo", emoji: true)

  b.section { |s| ... }
end
```

**Comment by CGA1123** [comment]
@rspeicher Yes, that would be nice to add in. I'll happily accept a PR that does that!

An oversight on my part to not have included this during the initial implementation in #57
