### ISSUE TITLE
Join the slack-ruby org?

### ISSUE THREAD

**Issue by dblock** [CGA1123/slack-ruby-block-kit#6]
Coming from https://github.com/slack-ruby/slack-ruby-client/issues/316.

Any interest in having slack_block_kit-ruby be part of the slack-ruby org? 

Potentially after renaming to slack-ruby-block-kit to be consistent? Not a must have ;)

**Comment by CGA1123** [comment]
Hey @dblock 😄 

Sounds like a good idea, don't have any issues with a rename either.
How would that work? Simply transferring ownership over to the `slack-ruby` org?

**Comment by dblock** [comment]
Maybe pitch in on that issue I linked to start? I don't think I want to have 2 projects. I'll take a look at the code of both soon and probably pick a winner :)

**Comment by CGA1123** [comment]
Closing -- general cleanup 🧹 


Happy to migrate under the `slack-ruby` org in the future if people prefer that, although there is no pressing need to at the moment.
